[     UTC     ] Logs for reconstruction-3d-from-2d.streamlit.app/

────────────────────────────────────────────────────────────────────────────────────────

[15:00:58] 🖥 Provisioning machine...

[15:00:58] 🎛 Preparing system...

[15:00:58] ⛓ Spinning up manager process...

[15:00:56] 🚀 Starting up repository: '3d-reconstruction-from-2d-images-', branch: 'main', main module: 'app.py'

[15:00:56] 🐙 Cloning repository...

[15:01:02] 🐙 Cloning into '/mount/src/3d-reconstruction-from-2d-images-'...
Updating files: 100% (105/105), done.

[15:01:02] 🐙 Cloned repository!

[15:01:02] 🐙 Pulling code changes from Github...

[15:01:04] 📦 Processing dependencies...


──────────────────────────────────────── uv ───────────────────────────────────────────


Using uv pip install.

Using Python 3.12.9 environment at /home/adminuser/venv

Resolved 91 packages in 751ms

Prepared 91 packages in 13.37s

Installed 91 packages in 1.34s

 + addict==2.4.0

 + altair==5.5.0

 + asttokens==3.0.0

 + attrs==25.3.0

 + blinker==1.9.0

 + cachetools==5.5.2

 + certifi==2025.1.31

 + charset-normalizer==3.4.1[2025-04-08 15:01:20.397392] 

 + click==8.1.8

 + comm==0.2.2

 + configargparse==1.7

 + contourpy==1.3.1

 + cycler==0.12.1

 + dash==3.0.2

 + decorator==5.2.1

 + executing==2.2.0

 + fastjsonschema==2.21.1

 + flask==[2025-04-08 15:01:20.397652] 3.0.3

 + fonttools==4.57.0

 + gitdb==4.0.12

 + gitpython==3.1.44

 + idna==3.10

 + importlib-metadata==8.6.1

 + ipython==9.1.0

 + ipython-pygments-lexers==1.1.1

 +[2025-04-08 15:01:20.397877]  ipywidgets==8.1.5

 + itsdangerous==2.2.0

 + jedi==0.19.2

 + jinja2==3.1.6

 + joblib==1.4.2

 [2025-04-08 15:01:20.398091] + jsonschema==4.23.0

 + jsonschema-specifications==2024.10.1

 + jupyter-core==5.7.2

 + jupyterlab-widgets==3.0.13

 + kiwisolver==1.4.8

 + markdown-it-py==3.0.0

 + markupsafe==3.0.2

 + [2025-04-08 15:01:20.398332] matplotlib==3.10.0

 + matplotlib-inline==0.1.7

 + mdurl==0.1.2

 + narwhals==1.34.0

 + nbformat==5.10.4

 + nest-asyncio==1.6.0[2025-04-08 15:01:20.398577] 

 + numpy==2.0.2

 + open3d==0.19.0

 + opencv-python==4.11.0.86

 + packaging==24.2

 + pandas==2.2.3

 + parso==0.8.4[2025-04-08 15:01:20.398782] 

 + pexpect==4.9.0

 + pillow==10.4.0

 + platformdirs==4.3.7

 + plotly==6.0.1

 + prompt-toolkit==3.0.50

 +[2025-04-08 15:01:20.398933]  protobuf==5.29.4

 + ptyprocess==0.7.0

 + pure-eval==0.2.3

 + pyarrow==19.0.1

 + pydeck==0.9.1

 + [2025-04-08 15:01:20.399089] pygments==2.19.1

 + pyparsing==3.2.3

 + pyquaternion==0.9.9

 + python-dateutil==2.9.0.post0

 + pytz==2025.2

 + pyyaml==[2025-04-08 15:01:20.399259] 6.0.2

 + referencing==0.36.2

 + requests==2.32.3

 + retrying==1.3.4

 + rich==13.9.4

 + rpds-py==0.24.0[2025-04-08 15:01:20.399442] 

 + scikit-learn==1.6.1

 + scipy==1.15.1

 + setuptools==78.1.0

 + six==1.17.0

 + smmap==5.0.2

 +[2025-04-08 15:01:20.399624]  stack-data==0.6.3

 + streamlit==1.41.1

 + tenacity==9.1.2

 + threadpoolctl==3.6.0

 + toml==0.10.2

 + tornado==6.4.2

 + tqdm==4.67.1

 + traitlets==5.14.3

 + typing-extensions==4.13.1

 + tzdata==2025.2

 + urllib3==2.3.0

 + [2025-04-08 15:01:20.399945] watchdog==6.0.0

 + wcwidth==0.2.13

 + werkzeug==3.0.6

 + widgetsnbextension==4.0.13

 + zipp==3.21.0

Checking if Streamlit is installed

Found Streamlit version 1.41.1 in the environment

Installing rich for an improved exception logging

Using uv pip install.

Using Python 3.12.9 environment at /home/adminuser/venv

Audited 1 package in 5ms


────────────────────────────────────────────────────────────────────────────────────────


[15:01:23] 🐍 Python dependencies were installed from /mount/src/3d-reconstruction-from-2d-images-/requirements.txt using uv.

Check if streamlit is installed

Streamlit is already installed

[15:01:25] 📦 Processed dependencies!




────────────────────── Traceback (most recent call last) ───────────────────────

  /home/adminuser/venv/lib/python3.12/site-packages/streamlit/runtime/scriptru  

  nner/exec_code.py:88 in exec_func_with_error_handling                         

                                                                                

  /home/adminuser/venv/lib/python3.12/site-packages/streamlit/runtime/scriptru  

  nner/script_runner.py:579 in code_to_exec                                     

                                                                                

  /mount/src/3d-reconstruction-from-2d-images-/app.py:4 in <module>             

                                                                                

      1 import streamlit as st                                                  

      2 import numpy as np                                                      

      3 import matplotlib.pyplot as plt                                         

  ❱   4 import cv2                                                              

      5 import os                                                               

      6 import open3d as o3d                                                    

      7 from pathlib import Path                                                

                                                                                

  /home/adminuser/venv/lib/python3.12/site-packages/cv2/__init__.py:181 in      

  <module>                                                                      

                                                                                

    178 │   if DEBUG: print('OpenCV loader: DONE')                              

    179                                                                         

    180                                                                         

  ❱ 181 bootstrap()                                                             

    182                                                                         

                                                                                

  /home/adminuser/venv/lib/python3.12/site-packages/cv2/__init__.py:153 in      

  bootstrap                                                                     

                                                                                

    150 │                                                                       

    151 │   py_module = sys.modules.pop("cv2")                                  

    152 │                                                                       

  ❱ 153 │   native_module = importlib.import_module("cv2")                      

    154 │                                                                       

    155 │   sys.modules["cv2"] = py_module                                      

    156 │   setattr(py_module, "_native", native_module)                        

                                                                                

  /usr/local/lib/python3.12/importlib/__init__.py:90 in import_module           

                                                                                

     87 │   │   │   if character != '.':                                        

     88 │   │   │   │   break                                                   

     89 │   │   │   level += 1                                                  

  ❱  90 │   return _bootstrap._gcd_import(name[level:], package, level)         

     91                                                                         

     92                                                                         

     93 _RELOADING = {}                                                         

────────────────────────────────────────────────────────────────────────────────

ImportError: libGL.so.1: cannot open shared object file: No such file or 

directory

2025-04-08 15:01:35.132 Uncaught app execution

Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling

    result = func()

             ^^^^^^

  File "/home/adminuser/venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec

    exec(code, module.__dict__)

  File "/mount/src/3d-reconstruction-from-2d-images-/app.py", line 4, in <module>

    import cv2

  File "/home/adminuser/venv/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>

    bootstrap()

  File "/home/adminuser/venv/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap

    native_module = importlib.import_module("cv2")

                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ImportError: libGL.so.1: cannot open shared object file: No such file or directory

main
ykapil897/3d-reconstruction-from-2d-images-/main/app.py